# Generated by Django 4.1.1 on 2022-09-14 19:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(
                        db_column="title",
                        max_length=254,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "quote",
                    models.TextField(blank=True, db_column="quote", null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        db_column="reminder_thumbnail",
                        max_length=500,
                        upload_to="uploads/",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("expire_at", models.DateTimeField(db_column="expire_at")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Active"), (0, "InActive")],
                        db_column="status",
                        default=1,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "reminder", "managed": True},
        )
    ]
