# Generated by Django 4.1.1 on 2022-09-14 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reminder", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="quote",
            field=models.TextField(blank=True, db_column="quote", null=True),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="title",
            field=models.CharField(
                db_column="title",
                max_length=254,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
