# Generated by Django 4.1.1 on 2022-09-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reminder", "0002_alter_reminder_quote_alter_reminder_title")]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="event_date",
            field=models.DateTimeField(blank=True, db_column="event_date", null=True),
        )
    ]
