# Generated by Django 4.1.1 on 2022-09-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reminder", "0003_reminder_event_date")]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="image",
            field=models.ImageField(
                blank=True,
                db_column="reminder_thumbnail",
                max_length=500,
                null=True,
                upload_to="uploads/",
            ),
        )
    ]
