# Generated by Django 4.1.1 on 2022-09-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reminder", "0004_alter_reminder_image")]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="expire_at",
            field=models.DateTimeField(blank=True, db_column="expire_at", null=True),
        )
    ]
