# Generated by Django 4.1.1 on 2022-09-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reminder", "0005_alter_reminder_expire_at")]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="event_date",
            field=models.DateField(blank=True, db_column="event_date", null=True),
        )
    ]
