# Generated by Django 4.1.1 on 2022-09-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reminder", "0006_alter_reminder_event_date")]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="event_date",
            field=models.DateField(db_column="event_date"),
        )
    ]
